name: Scrape Websites and Post Events

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (UTC)

  workflow_dispatch:

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install Playwright browsers
      - name: Install Playwright browsers
        run: |
          python -m playwright install  # Installs the necessary browser binaries

      # Step 5: Run the scraping script
      - name: Run scraping script
        run: python scrape_and_post.py

    env:
      CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      CIRCLE_API_KEY: ${{ secrets.CIRCLE_API_KEY }}
      CIRCLE_COMMUNITY_ID: ${{ secrets.CIRCLE_COMMUNITY_ID }}
      CIRCLE_SPACE_ID: ${{ secrets.CIRCLE_SPACE_ID }}
